# Generated by Django 5.2.11 on 2026-03-29 10:19

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('n1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('post', django.db.models.manager.Manager()),
            ],
        ),
    ]
