# Generated by Django 5.2.11 on 2026-03-29 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('n1', '0002_alter_post_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
            ],
        ),
    ]
