# Generated by Django 5.2.11 on 2026-03-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('n1', '0004_na_alter_post_options_post_post_all_title_71a804_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='na',
            options={'managed': True, 'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='na',
            name='name',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterModelTable(
            name='na',
            table='na_all',
        ),
    ]
