# Generated by Django 5.2.11 on 2026-03-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('n1', '0005_alter_na_options_alter_na_name_alter_na_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'ba_all',
                'ordering': ['name'],
                'abstract': False,
                'managed': True,
            },
        ),
    ]
