# Generated by Django 5.2.11 on 2026-03-29 19:19

import django.db.models.deletion
import n1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('n1', '0009_autor_alter_book_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='usser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='n1.user')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(default=n1.models.get_default_user, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='profile_default', to='n1.user')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileNull',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_null', to='n1.user')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileProtect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='profile_protect', to='n1.user')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileRestrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='profile_restrict', to='n1.user')),
            ],
        ),
    ]
