# Generated by Django 5.2.11 on 2026-03-29 20:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('n1', '0011_names_namesproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='uuidmodel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='uuidsmodel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
