# Generated by Django 5.2.11 on 2026-03-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('n1', '0012_uuidmodel_uuidsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
