# Generated by Django 5.2.11 on 2026-03-29 20:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('n1', '0013_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uuidsmodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid7, primary_key=True, serialize=False),
        ),
    ]
