# Generated by Django 5.2.11 on 2026-03-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('n1', '0014_alter_uuidsmodel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('images', models.ImageField(blank=True, upload_to='images/')),
                ('docu', models.FileField(blank=True, upload_to='documents/')),
            ],
        ),
    ]
